FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.roomcast.txt /app/requirements.roomcast.txt
RUN pip install --no-cache-dir -r /app/requirements.roomcast.txt

COPY . /app

EXPOSE 1967

CMD ["gunicorn", "-w", "1", "--threads", "24", "-b", "0.0.0.0:1967", "roomcast_server:app"]
